name: Pull secrets

on:
  workflow_dispatch

jobs:
  pullakv:
    runs-on: ubuntu-latest
    steps:
      - name: Update Storage Secrete
        shell: pwsh
        run: |
          az login --service-principal --username ${{ secrets.clientid }} --password ${{ secrets.clientsecret }} --tenant ${{ secrets.tenantid }} --allow-no-subscriptions
          
          $functionAppName = 'functionapp_name'
          $functionAppRg = 'resource_group_name'

          $functionAppId = az functionapp show -n $functionAppName -g $functionAppRg --query "id"
          az rest --method post --url https://management.azure.com/$functionAppId/config/configreferences/appsettings/refresh?api-version=2022-03-01
